# https://taskfile.dev

version: "3"

tasks:
  clear:
    vars:
      PROJECT_NAME: "cfg-server"
    cmds:
      - rm -f ./{{.PROJECT_NAME}} coverage.out
      - rm -rf base/*
      - rm -rf ./repo/{..?*,.[!.]*,*} 2>/dev/null

  build:
    cmds:
      - go build .
    silent: true

  build-release:
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h
      GIT_BRANCH:
        sh: git name-rev --name-only {{.GIT_COMMIT}}
      BUILDNUM: '{{.BUILDNUM| default "1"}}'
      BUILD_TIMESTAMP:
        sh: date -u +'%Y-%m-%dT%H:%M:%SZ'
    cmds:
      - go build -ldflags="-X main.aGitHash={{.GIT_COMMIT}} -X main.aGitBranch={{.GIT_BRANCH}} -X main.aBuildNumber={{.BUILDNUM}} -X main.aBuildTimeStamp={{.BUILD_TIMESTAMP}}" .

  lint:
    cmds:
      - golangci-lint run ./...

  test:
    cmds:
      - go test ./... -v --coverprofile=coverage.out
    silent: true
